server {
    listen 80;

    server_name sharkids.nimbuscloud.mx;
    
### Codigo 301 - Moved Permanently
    return 301 https://$host$request_uri;
	
    # Proxy para api, reedirije el trafico al servicio de docker sharkids-api
    location /api/ {
        proxy_pass http://sharkids-api:3000/;  
    }



### NOTA:
### Esto solo deberia estar descomentado cuando no tengas certificado
### https.

    #root /usr/share/nginx/html;
    #index index.html;

    #location / {
    # try_files $uri $uri/ /index.html;
    #}

####
###
###
    error_page 404 /index.html;
}
# Bloque HTTPS con certificados y proxy inverso
server {
    listen 443 ssl http2;
    server_name sharkids.nimbuscloud.mx;

    # Rutas a tus certificados Let's Encrypt
    ssl_certificate     /etc/letsencrypt//fullchain1.pem;
    ssl_certificate_key /etc/letsencrypt/privkey1.pem;

    root /usr/share/nginx/html;
    index index.html;


    location /api/ {
        proxy_pass http://sharkids-api:3000/;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }

    # Si deseas mantener una página de fallback (por ejemplo, para apps SPA)
    #error_page 404 /index.html;
}
