server {
    listen 80;

    server_name sharkids.nimbuscloud.mx;

    root /usr/share/nginx/html;
    index index.html;

    location / {
     try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}
# Bloque HTTPS con certificados y proxy inverso
#server {
   # listen 443 ssl http2;
    #server_name sharkids.nimbuscloud.mx;

    # Rutas a tus certificados Let's Encrypt
    #ssl_certificate     /etc/letsencrypt/live/ironcat.nimbuscloud.mx/fullchain1.pem;
    #ssl_certificate_key /etc/letsencrypt/live/ironcat.nimbuscloud.mx/privkey1.pem;

    #root /usr/share/nginx/html;
    #index index.html;


    #location / {
     #   try_files $uri $uri/ /index.html;
#    proxy_pass         http://localhost:8080;
    #    proxy_set_header   Host $host;
    #    proxy_set_header   X-Real-IP $remote_addr;
    #    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    #    proxy_set_header   X-Forwarded-Proto $scheme;
    #}

    # Si deseas mantener una página de fallback (por ejemplo, para apps SPA)
    #error_page 404 /index.html;
#}
